baseURL = "https://mattgu314.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Your Name"
  description = "A blog built with Hugo and PaperMod"
  defaultTheme = "auto" # dark, light, or auto
  showReadingTime = true
  showToc = true
  showTags = true
  showCategories = true
  enableSearch = true

[taxonomies]
  tag = "tags"
  category = "categories"