baseURL = "https://mattgu314.github.io/"
theme = "PaperMod"
publishDir = "docs"

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "Matt's Blog"
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
  [languages.zh]
    contentDir = 'content'
    disabled = false
    languageCode = 'zh-cmn'
    languageDirection = 'ltr'
    languageName = 'Chinese'
    title = 'Matt 的小站'
    weight = 2
    [languages.zh.params]
      subtitle = '欢迎作客！'

[params]
  author = "Matt Gu"
  description = "A blog built with Hugo and PaperMod"
  defaultTheme = "auto" # dark, light, or auto
  showReadingTime = true
  showToc = true
  showTags = true
  showCategories = true
  enableSearch = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "Welcome to Matt's Site!"
  Content = "This is my personal blog where I share insights and stories. Enjoy your stay!"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
